class DatabaseContext(object):
    DATA_FOLDER = 'data/'
    DEFAULT_RESULTS_SIZE = 10
    DEFAULT_RESULTS_SKIP = 0
    LOCKING_CYCLE = 0.01
    THREADS_CYCLE = 0.1
    MAX_DOC_PER_FILE = 100000
    MAX_THREADS = 24
